name: flutter_search_bar
description: A (mostly) automatic search bar inside an AppBar for flutter
version: 2.0.5
homepage: https://frozor.io
author: Spencer <spencer@frozor.io>

environment:
  sdk: '>=1.20.1 <=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5

flutter:
  uses-material-design: true

dev_dependencies:
  test: ^0.12.0
